### ISSUE TITLE
Doc website has strange appearance in IE9 and FF40

### ISSUE THREAD

**Issue by veggiespam** [Contrast-Security-OSS/docs#2]
Attached are screen shots of the website in both IE9 and FF40.  The page is not fully drawn on screen.  I'm not sure if this is because off-site components are blocked Corporate Proxy/Firewall or if the browser is too old.  I think jquery and zendesk assists are properly loaded.

![ie-9](https://cloud.githubusercontent.com/assets/3471999/10738498/10b76d1a-7bee-11e5-92ef-dd006cb74f55.png)
![ff-40](https://cloud.githubusercontent.com/assets/3471999/10738501/124bc0cc-7bee-11e5-8367-cb82beae4ec2.png)

**Comment by veggiespam** [comment]
The site platform.twitter.com is banned by the proxy.  That might be causing the load issues.

**Comment by SteveFeldman** [comment]
We will take a look at the two browsers in question and try to figure out what's not loading correctly. Thanks for bringing this to our attention.

**Comment by cgtwin** [comment]
@SteveFeldman You need to use overflow:auto instead of overflow:scroll

**Comment by terra4383** [comment]
@veggiespam This issue should now be resolved. Please let us know if you continue to see problems. Thank you!

**Comment by veggiespam** [comment]
It still does not look good.  The only difference now is that second scroll bar is not present.  The text of the ToC is still cropped and word-wrapped at above half of the width of the window pane.

**Comment by terra4383** [comment]
Ok thank you for the update. We have it working in IE 11 and FF 41, but we will try to figure out what's going on.

**Comment by veggiespam** [comment]
IE9 screen shot from today is attached.

![IE 9](https://cloud.githubusercontent.com/assets/3471999/11477200/dc9e8c7a-9754-11e5-9c21-06d4f3db938d.png)

**Comment by terra4383** [comment]
Thank you for the update.  We recently pushed a fix for this, so please let us know if you still have issues.  You may see a minor centering issue with the logo, which is currently being addressed.
